<?php

namespace AppBundle\Repository;

/**
 * BlogPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogPostRepository extends \Doctrine\ORM\EntityRepository {

  public function findRecentPosts($limit) {

    return $this->getEntityManager()
      ->createQuery("SELECT a FROM AppBundle:BlogPost a ORDER BY a.id DESC")
      ->setMaxResults($limit)
      ->getResult();

  }

  public function findPopularPosts($limit) {

    return $this->getEntityManager()
      ->createQuery("SELECT a FROM AppBundle:BlogPost a ORDER BY a.id DESC")
      ->setMaxResults($limit)
      ->getResult();

  }

}
